# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: DockerCompose@0
  inputs:
    action: 'run Services'
    dockerComposeFile: tests/DenryuRebalancer.IntegrationTests/docker-compose.yml

- script: './build.sh'

- script: './test.sh'

- script: './test-integration.sh'