# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: sonarqube.f6fd523bd4f040399d3c.westus2.aksapp.io
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 'tokyo.hashhub.denryu.rebalancer'
    cliProjectName: 'Denryu Rebalancer'
    cliProjectVersion: 0.0.0
    cliSources: src
    extraProperties: |
     # Additional properties that will be passed to the scanner, 
     # Put one key=value per line, example:
     # sonar.exclusions=**/*.bin

- task: DockerCompose@0
  inputs:
    action: 'run Services'
    dockerComposeFile: tests/DenryuRebalancer.IntegrationTests/docker-compose.yml

- script: './build.sh'

- script: './test.sh'

- script: './test-integration.sh'

- task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

steps:
- task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
  displayName: 'Publish Quality Gate Result'
